### ISSUE TITLE
Example with additional query search parameters?

### ISSUE THREAD

**Issue by cboettig** [brazil-data-cube/rstac#104]
I cannot figure out how to use the `q` argument of the `stac_search()` function.

In the python client, a user can specify arbitrary search criteria as a JSON string, e.g. to filter for images with less than 10% cloud-cover, you can do:

```
catalog = Client.open("https://planetarycomputer.microsoft.com/api/stac/v1")

search = catalog.search(
    collections=["sentinel-2-l2a"],
    intersects=area_of_interest,
    datetime=time_of_interest,
    query={"eo:cloud_cover": {"lt": 10}},
)
```

see full example from [Microsoft Planetary Computer notebook](https://planetarycomputer.microsoft.com/dataset/sentinel-2-l2a#Example-Notebook).  In the R client, I see the argument `q` which says it takes an `RSTACQuery` object, but the docs for that have no examples and I cannot figure out the syntax.  I tried the below but this clearly isn't correct.  It would be great if we could pass an R list or json string directly to `q`

```
s_obj <- stac("https://planetarycomputer.microsoft.com/api/stac/v1/")

it_obj <- s_obj %>% 
  stac_search(collections = "sentinel-2-l2a",
              #intersects = polygon$geometry[[1]]
              bbox = bbox,
              datetime = "2019-06-01/2019-08-01",
              q=RSTACQuery(params = list("eo:cloud_cover" = list("lt"= 10)))
              ) %>%
  get_request() %>% # intersects needs post
  items_sign(sign_fn = sign_planetary_computer())
```

**Comment by OldLipe** [comment]
**rstac** has a basic function for search, `stac_search()`, and implements extensions in separate functions. 
Advanced search criteria can be requested by the `ext_query()` function, which implements the [query extension](https://github.com/radiantearth/stac-api-spec/tree/master/fragments/query) of the STAC API. 
 
The following example is based on your code: 
 
```r
s_obj <- stac("https://planetarycomputer.microsoft.com/api/stac/v1/")
bbox <- c(-56.4185, -12.0250, -55.8765,-11.6522)

it_obj <- s_obj %>% 
    stac_search(collections = "sentinel-2-l2a",
                bbox = bbox,
                datetime = "2019-06-01/2019-08-01") %>%
    ext_query("eo:cloud_cover" < 0.1) %>%
    post_request()
```
To access the assets of the items returned by the Microsoft Planetary Computer catalog it is necessary to include
a token in the urls using the `items_sign` function (as you have done):

```r
it_obj <- it_obj %>% 
    items_sign(sign_fn = sign_planetary_computer())
```
 
The `ext_query()` function allows using operators to create complex search criteria based on item properties. 

The `q` parameter in the functions refers to the `RSTACQuery` object that stores the search criteria. All functions preceding the request (`get_request` and `post_request`) are fed by and return this object. So you can use them with the pipe operator (`%>%`).
 
We will include more examples in the next version of the package.
