### ISSUE TITLE
unexpected error in stac_search parsing JSON?

### ISSUE THREAD

**Issue by cboettig** [brazil-data-cube/rstac#112]
The following search against a common stac API fails with error

```
Error: lexical error: invalid char in json text.
                                       Unexpected token , in JSON at p
                     (right here) ------^
```                     

reprex:
```r
library(sf)
library(rstac)
coords <- c(xmin=-86.94663, ymin=33.43930, 
            xmax=-86.67684, ymax=33.62239)
bbox <- st_bbox(coords, crs=4326) # Birmingham, AL
matches <- 
  stac("https://earth-search.aws.element84.com/v0/") |>
  stac_search(collections = "sentinel-2-l2a-cogs",
              bbox = bbox,
              datetime = "2019-06-01/2019-08-01"
              ) |>
  get_request() 
```

Not sure what is going wrong, the `sentinel-2-l2a-cogs/items` JSON looks fine from the browser I think.  This search is also fine with planetary computer version of the sentinel-2-l2a catalog, but I'd like it to work with other catalogs. 

Relatedly but I'm not sure if it's out of scope: can `rstac` help users to work with STAC catalogs that do not also implement their own stac API?

**Comment by OldLipe** [comment]
Hi @cboettig. 

In the AWS STAC API, there is no **GET** implementation for the `search` endpoint. Here is an example:

```
https://earth-search.aws.element84.com/v0/search?collections=sentinel-s2-l2a-cogs&datetime=2019-06-01/2019-08-01&bbox=-86.94663,33.4393,-86.67684,33.62239
```
Notice that the return is not a JSON. This is why you get this error in the parse of rstac. 
We will improve this message in the new version of rstac.

To do your query in AWS STAC, I just changed the method to **POST** and removed the class from the `bbox` parameter:

```R
library(sf)
library(rstac)
coords <- c(xmin=-86.94663, ymin=33.43930, 
            xmax=-86.67684, ymax=33.62239)
bbox <- st_bbox(coords, crs=4326) # Birmingham, AL
matches <- 
    stac("https://earth-search.aws.element84.com/v0/") |>
    stac_search(collections = "sentinel-s2-l2a-cogs",
                bbox = c(bbox),
                datetime = "2019-06-01/2019-08-01"
    ) |>
    post_request() 
```
We are working on an implementation to support static catalogs in next versions of rstac packages.

**Comment by cboettig** [comment]
wonderful, thanks so much!

Will keep my eyes out for support for static catalogs.  really cool
