### ISSUE TITLE
sign_planetary_computer() does not work as expected

### ISSUE THREAD

**Issue by cboettig** [brazil-data-cube/rstac#114]
Here's a small reprex:

```r

latitude = 38.6
longitude = -121.5
buffer = 1
coords = c(longitude - buffer, latitude - buffer, longitude + buffer, latitude + buffer)
library(rstac)

matches <- 
  stac("https://planetarycomputer.microsoft.com/api/stac/v1") |>
  stac_search(collections = "modis-13A1-061",
              bbox = coords,
              limit = 10) |>
  post_request() |>
  items_sign(sign_fn = sign_planetary_computer()) 


paste0("/vsicurl/",
matches$features[[1]]$assets$`500m_16_days_EVI`$href) |> 
  stars::read_stars() |> plot()
```

I get a 403 access error.  

This is  a simplified example of my attempt to translate from the Planetary Computer's jupyter/python example: https://planetarycomputer.microsoft.com/dataset/modis-15A2H-061#Example-Notebook, which I can confirm still works on the planetary computer at least.  Not sure if this access issue is expected?

**Comment by OldLipe** [comment]
Hi @cboettig. 

I was able to reproduce the error. I think it may be an issue in the signature of this collection. 
Using the Sentinel-2 collection worked:

```r
latitude = 38.6
longitude = -121.5
buffer = 1
coords = c(longitude - buffer, latitude - buffer, longitude + buffer, latitude + buffer)
library(rstac)

matches <- 
  stac("https://planetarycomputer.microsoft.com/api/stac/v1") |>
  stac_search(collections = "sentinel-2-l2a",#collections = "modis-13A1-061",
              bbox = coords,
              limit = 10) |>
  post_request() |>
  items_sign(sign_fn = sign_planetary_computer()) 


paste0("/vsicurl/", matches$features[[1]]$assets$B01$href) |> 
  stars::read_stars() |> plot()
```
I will take a look if for this collection the signature pattern is different.

**Comment by cboettig** [comment]
@OldLipe thanks. Yes, also noticed I could access sentinel2 okay. I think perhaps the signature isn't needed for the access to sentinel?  My colleague @PMassicotte pointed me to https://planetarycomputer.microsoft.com/docs/reference/sas/ , if you manually paste one of the href URLs in there to sign, you get back a curl request, which if you run it, returns a correctly signed URL that you can then use as expected (I haven't pasted the signed URLs here since they automatically expire and  that would just become confusing).  

So we think something is up with `sign_planetary_computer()` routine, but not sure what. He noticed that <https://planetarycomputer.microsoft.com/api/sas/v1/token> isn't working, but then again the same URL appears on the python side where everything seems to work just fine (https://github.com/microsoft/planetary-computer-sdk-for-python/blob/7970d3bda89f4dbd052516cd1df52b00b658d855/planetary_computer/settings.py#L8).

**Comment by PMassicotte** [comment]
_Manually_ signing a file seems to be working: 

```r
library(httr)

url <- GET("https://planetarycomputer.microsoft.com/api/sas/v1/sign?href=https://modiseuwest.blob.core.windows.net/modis-061-cogs/MYD13A1/08/05/2022297/MYD13A1.A2022297.h08v05.061.2022315120509_500m_16_days_NDVI.tif") |>
  content()

terra::rast(url$href)
```

**Comment by cboettig** [comment]
weirdly the above manually signing fails for me, but I can still confirm the basic trick from @PMassicotte works:

```r
library(rstac)
library(httr)

latitude = 38.6
longitude = -121.5
buffer = 1
coords = c(longitude - buffer, latitude - buffer, longitude + buffer, latitude + buffer)

matches <- 
  stac("https://planetarycomputer.microsoft.com/api/stac/v1") |>
  stac_search(collections = "modis-13A1-061",
              bbox = coords,
              limit = 10) |>
  post_request() |>
  items_sign(sign_fn = sign_planetary_computer()) 


href <- matches$features[[1]]$assets$`500m_16_days_EVI`$href

x <- parse_url(href)
y <- glue::glue("{scheme}://{hostname}/{path}", scheme = x$scheme, hostname = x$hostname, path = x$path)
url <- GET(paste0("https://planetarycomputer.microsoft.com/api/sas/v1/sign?href=", y)) |>
  content()

paste0("/vsicurl/",url$href) |>  
  stars::read_stars() |> plot()
```

**Comment by OldLipe** [comment]
It seems there is an issue with the token generation service for this `modis-13A1-061` collection. We have opened an issue at Planetary Computer to investigate the problem.   
Issue: https://github.com/microsoft/PlanetaryComputer/discussions/131#discussion-4567750

**Comment by OldLipe** [comment]
Hi @cboettig,

We have implemented the new MPC signature function in our development branch. 
I created a gist with your example: https://gist.github.com/OldLipe/bf76fcf59e1f7a8549d67f3827383a02

**Comment by cboettig** [comment]
Thanks @OldLipe , looks great.  (I think the gist is missing the definitions of some internal variables/functions though so I can't run it yet).  Which is the development branch?

**Comment by OldLipe** [comment]
@cboettig, thanks for letting me know. My bad. 
I just updated the gist: https://gist.github.com/OldLipe/bf76fcf59e1f7a8549d67f3827383a02

My rstac development branch: https://github.com/OldLipe/rstac/tree/b-0.9.1

**Comment by cboettig** [comment]
Thanks @OldLipe , the fix in the gist is perfect, have been happily using that.  

Maybe it's just me, but I did try installing the dev branch you mentioned, `remotes::install_github("OldLipe/rstac@b-0.9.1")`, but that doesn't seem to have the MPC signature fix?  thanks!  Really appreciate all you do, this package is amazing.

**Comment by OldLipe** [comment]
Hi @cboettig,

Yes, the MPC signature fix is in this branch. I tested this version in a new environment and I was able to reproduce your example. 

Make sure after installing rstac (dev branch) that the package version is `0.9.1.6`. 

You can use the following command:
```R
packageVersion("rstac")
```
In a couple of days we will send this version to CRAN.

**Comment by cboettig** [comment]
thanks, yup! got it now, all working.  Looking forward to seeing it on CRAN! I'll close this out now.
