### ISSUE TITLE
Download all matched features

### ISSUE THREAD

**Issue by koichisato-dev** [brazil-data-cube/rstac#116]
Hi. Thank you for creating this useful package.

Is it possible to download all matched features with the same item at one time? I have no idea on how to download all features with the same item at one time after finding them using "stack_searc". 

Let's say, I can get 12 matched features with the command below.

`search <- stac("https://earth-search.aws.element84.com/v0")`

`result2017 <- search %>%
  stac_search(collections = "sentinel-s2-l2a-cogs",
bbox = c(140.47, 36.34, 140.60, 36.43),
                     datetime = "2017-01-01/2017-12-31") %>% 
  post_request() %>% 
  items_fetch() %>% 
  items_filter(filter_fn = function(x) {x[["eo:cloud_cover"]] < 1})`

And after this, to download the asset "B01" for all the matched features, I did the following:

`download_assets <- result2017 %>%
                                      assets_download(asset_names = "B01", items_max = 12)`

However, what I got was the asset "B01.tif" only for the latest feature, not all the matched features.

I appreciate if you kindly provide any advice.

**Comment by OldLipe** [comment]
Hi @koichisato-dev,

Thank you for reporting this bug. We have fixed it and it will be available in this new version (`0.9.2`). 

I will reopen editing until the release of `0.9.2`.

**Comment by koichisato-dev** [comment]
Hello @OldLipe,

Thank you for your response and trying to fix it.

Now, I am virtually accessing to any bands of all matched features by combining loop and GDAL Virtual File Systems, but it would be better if I can download the bands on my local environment, as one option.

I will wait for the new version. Thanks.

**Comment by OldLipe** [comment]
Hi @koichisato-dev,

The new version of `rstac` is available. Thanks for reporting this issue!
