### ISSUE TITLE
Adding function to convert STACItemCollection to raster/terra R package

### ISSUE THREAD

**Issue by agronomofiorentini** [brazil-data-cube/rstac#144]
**Describe the requested improvement**
Dear developers, I would like to know if there is a function or a way to be able to convert STACitemcollection to the most common raster formats in R,

**Additional context**
This allows you to be able to perform operations that you are fully aware of

Thanks so much for developing this R package.

**Comment by rolfsimoes** [comment]
Hi @agronomofiorentini !
Using [geojsonsf](https://github.com/SymbolixAU/geojsonsf) you will be able to convert STACItemCollection into `sf` objects. We also added support to do this natively in `rstac` (PR #147). It will be available on CRAN soon.
