### ISSUE TITLE
No effect when using `ext_filter()`

### ISSUE THREAD

**Issue by kadyb** [brazil-data-cube/rstac#145]
It seems that in the following example the ```ext_filter(`eo:cloud_cover` < 50)``` is not working properly.

```r
library("rstac") # ‘0.9.2.5’

stac("https://earth-search.aws.element84.com/v1") %>%
  stac_search(collections = "sentinel-2-l2a", limit = 20) |>
  ext_filter(`eo:cloud_cover` < 50) |>
  post_request() -> items

unlist(lapply(items$features, \(x) x$properties$"eo:cloud_cover"))
# [1] 27.331108 26.458439 19.258478 20.978947 67.034644 51.456231 29.494283 16.349749
# [9] 18.936606 17.784585 25.580233 26.147965  7.001264  5.166382 93.213230 69.003659
# [17] 67.372113 99.531114 87.581521 84.973758
```

**Comment by anadefreitas** [comment]
@kadyb, the AWS does not implement filter extension, but we can use the query one.

```R
stac("https://earth-search.aws.element84.com/v1") %>%
    stac_search(collections = "sentinel-2-l2a", limit = 20) |>
    ext_query(`eo:cloud_cover` < 50) |>
    post_request() -> items

unlist(lapply(items$features, \(x) x$properties$"eo:cloud_cover"))
[1] 27.331108 26.458439 19.258478 20.978947 29.494283 16.349749 18.936606
[8] 17.784585 25.580233 26.147965  7.001264  5.166382 47.935012 43.832543
[15] 43.000436 44.263372 44.396487 16.639401 41.339231 46.211138
```

**Comment by kadyb** [comment]
Thanks!

**Comment by kadyb** [comment]
It may be worth adding to the `ext_filter()` docs that this must be supported by the server / data provider, and if it is not, `ext_query()` can be used. Or another solution might be to return a warning.

**Comment by MOB-Habitat** [comment]
Same here, I'm trying to filter out only certain months

```
items <- stac("https://cmr.earthdata.nasa.gov/stac/LPCLOUD/") |> 
  stac_search(collections = list("HLSS30_2.0", "HLSL30_2.0"),
              bbox = c(-73.72, 45.55, -73.53, 45.57),
              limit = 100,
              datetime = '1984-07-01T00:00:00Z/2024-09-15T23:59:59Z'
              ) |> 
  rstac::ext_filter(
      datetime > "2016-07-01"
  ) |>
  post_request()

print(items)

```

The NASA website specifies that https://cmr.earthdata.nasa.gov/search/site/docs/search/api.html#temporal-range-searches there is temporal range selection possible, but I'm not able to make it work for selected dates. For example, I'd like to get all the years that are between the month of 1st of july and 15th of september.  But it doesn't work.

**Comment by OldLipe** [comment]
Hi @MOB-Habitat,

It appears that you are attempting to use the `filter` extension on a STAC endpoint that does not support this implementation. However, Earth Data implements the `query` extension, which I think could help you.

To check the conformances and extensions implemented by this STAC endpoint:

```r
rstac::stac("https://cmr.earthdata.nasa.gov/stac/LPCLOUD/") |>
    rstac::conformance() |>
    rstac::get_request()
``` 

I tried to use the `query` extension but was unsuccessful. Therefore, I find it easier to filter the items after the request:

```r
items <- stac("https://cmr.earthdata.nasa.gov/stac/LPCLOUD/") |> 
    stac_search(collections = list("HLSS30_2.0", "HLSL30_2.0"),
                bbox = c(-73.72, 45.55, -73.53, 45.57),
                limit = 100,
                datetime = '1984-07-01T00:00:00Z/2024-09-15T23:59:59Z'
    ) |>
    post_request()

library(lubridate)

# Filtering each item using a filter function 
items_filtered <- items_filter(
    items, filter_fn = function(item) {
        item_datetime <- item[["properties"]][["datetime"]]
        
        lubridate::month(item_datetime) >= 7 && 
            lubridate::day(item_datetime) >=  1 &&  
            lubridate::month(item_datetime) <= 9 && 
            lubridate::day(item_datetime) >=  15
    }
)

items_datetime(items_filtered)
```

**Comment by MOB-Habitat** [comment]
Thanks a lot for this! However, it seems that the even setting the `limit = 2000`, I can't get more than 100. So I still need to loop the year combinations... 

In this case, since the endpoint is not supporting it, it could be nice to have a way to loop through all year-month-day combinations in a `items_all` object and then combine each `items` in the list to a master list that can be used in a script. 

Dos that make sense? Is there a way to do this already?

**Comment by OldLipe** [comment]
Hi @MOB-Habitat, 

Yes. We provide a pagination function `items_fetch()`. It allows you to retrieve all the items in the collection.
