### ISSUE TITLE
What is the recommended workflow for grouping bands from the same scene?

### ISSUE THREAD

**Issue by kadyb** [brazil-data-cube/rstac#152]
Is there any better way to create multiband rasters from URLs? And maybe you should implement a function to group the same scenes?

```r
library("rstac")
library("terra")

stac("https://earth-search.aws.element84.com/v1") |>
  stac_search(collections = "sentinel-2-l2a", bbox = c(16, 53, 17, 54), limit = 2) |>
  post_request() |>
  assets_select(asset_names = c("blue", "green", "red")) |>
  assets_url(append_gdalvsi = TRUE) -> urls

group_urls = function(x, n) {
  group = strsplit(x, "/", fixed = TRUE)
  group = sapply(group, "[[", n)
  group = split(x, factor(group))
  return(group)
}

x = group_urls(urls, n = 12)
# $S2A_33UWU_20240214_0_L2A
# [1] "/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/33/U/WU/2024/2/S2A_33UWU_20240214_0_L2A/B02.tif"
# [2] "/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/33/U/WU/2024/2/S2A_33UWU_20240214_0_L2A/B03.tif"
# [3] "/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/33/U/WU/2024/2/S2A_33UWU_20240214_0_L2A/B04.tif"
# 
# $S2A_33UXU_20240214_0_L2A
# [1] "/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/33/U/XU/2024/2/S2A_33UXU_20240214_0_L2A/B02.tif"
# [2] "/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/33/U/XU/2024/2/S2A_33UXU_20240214_0_L2A/B03.tif"
# [3] "/vsicurl/https://sentinel-cogs.s3.us-west-2.amazonaws.com/sentinel-s2-l2a-cogs/33/U/XU/2024/2/S2A_33UXU_20240214_0_L2A/B04.tif"

sapply(x, vrt, options = "-separate")
```

**Comment by rolfsimoes** [comment]
Dear @kadyb ,

Apologize for my delay in responding to your issue. Thank you for your patience.

In this case, you can use the function `items_reap()`. This function allows you to pick elements of a STAC Item in depth. Here’s an example:

```r
library("rstac")

stac("https://earth-search.aws.element84.com/v1") |>
  stac_search(collections = "sentinel-2-l2a", bbox = c(16, 53, 17, 54), limit = 2) |>
  post_request() |>
  assets_select(asset_names = c("blue", "green", "red")) |> 
  items_reap(c("assets", "*"), \(x) x$href)
```

To achieve the same structure you mentioned, you can include these two steps:

```r
# ... |> 
  purrr::map(\(x) unname(unlist(x))) |> 
  magrittr::set_names(items_reap(items, "id")) -> urls
```

The `items_reap()` function is particularly useful for extracting nested elements from STAC items. The use of `*` in the `items_reap()` parameter indicates that we want to extract all sub-elements under the specified path. In this case, `c("assets", "*")` means we are interested in retrieving all the assets associated with each STAC item, regardless of their specific names. This wildcard selection is a powerful feature that simplifies the process of accessing all relevant URLs.

Unfortunately, I realized that the documentation does not currently highlight this feature of the `items_reap()` function. I appreciate you bringing this to my attention.

Please let me know if you have any further questions or need additional assistance. I hope this helps with your project!

Best regards,
Rolf

**Comment by kadyb** [comment]
Great, thank you for explaining!
