### ISSUE TITLE
Website is out of date?

### ISSUE THREAD

**Issue by mikemahoney218** [brazil-data-cube/rstac#153]
Hi all! Congrats on 1.0.0, I'm really excited to see it.

It looks like the GitHub pages website is still stuck on 0.9.2-1, however: https://brazil-data-cube.github.io/rstac/

Looking at the `gh-pages` branch, it looks like the website was last updated sometime last year: https://github.com/brazil-data-cube/rstac/tree/gh-pages

If you want the website to update automatically, you might consider using the pkgdown GitHub action from R-lib: https://github.com/r-lib/actions/blob/v2-branch/examples/pkgdown.yaml

**Comment by rolfsimoes** [comment]
Hi @mikemahoney218, thanks to let us know about this.

We are going fix this soon. I will keep you updated

**Comment by OldLipe** [comment]
Hi @mikemahoney218, We've just updated. Thanks!
