### ISSUE TITLE
Static Catalogs

### ISSUE THREAD

**Issue by m-mohr** [brazil-data-cube/rstac#21]
I was very happy to see an R package for STAC evolve, great work! Later in the README it seems to suggest that this package only supports STAC APIs, but not static catalogs. Is that true? If yes, are there plans to support static catalogs?

**Comment by gqueiroz** [comment]
Hi @m-mohr ,

Many thanks for the contact. 
@rolfsimoes and @OldLipe are the most active developers of this R-package.

Indeed, this is would be a very good addition to the package. I am sure that @OldLipe could help us on that. Do you want to share some thoughts in an issue or even propose something?

**Comment by cboettig** [comment]
any news on this?

**Comment by OldLipe** [comment]
Hi @cboettig,

We will start working on this feature and we hope to have it included in the next version of the package (version 1.0.0). We will keep you updated on our progress. 

If you have any further suggestions or feedback, please don't hesitate to let us know.

**Comment by rolfsimoes** [comment]
This feature is now on the way: #147
