### ISSUE TITLE
Adjust download helpers to access data from Microsoft's Planetary Computer

### ISSUE THREAD

**Issue by TomAugspurger** [brazil-data-cube/rstac#36]
As shown in https://gist.github.com/TomAugspurger/4cd0e70c51f7af8d6b1d747c249ea4c4#gistcomment-3763228, the STAC endpoint from Microsoft's Planetary Computer is open and publicly accessible, e.g. [this STAC Item](https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/items/S2B_MSIL2A_20210909T215909_R086_T01LHD_20210910T045920) can be viewed without any authentication. However, the actual assets, e.g. the [B02 band](https://sentinel2l2a01.blob.core.windows.net/sentinel2-l2/01/L/HD/2021/09/09/S2B_MSIL2A_20210909T215909_N0300_R086_T01LHD_20210910T045920.SAFE/GRANULE/L2A_T01LHD_A023564_20210909T215910/IMG_DATA/R10m/T01LHD_20210909T215909_B02_10m.tif) are private. Following that link will give a 404 error.

To actually download an asset, users need to "sign" the asset URLs by appending a token. Tokens can be generated (even anonymously) by making an HTTP request to `https://planetarycomputer.microsoft.com/api/sas/v1/token/<storage-account>/<storage-container>`, e.g. https://planetarycomputer.microsoft.com/api/sas/v1/token/sentinel2l2a01/sentinel2-l2 for Sentinel 2 Level 2A. That returns a JSON response with a `token` field. Appending that token to the asset URL results in a valid URL that can be used with GDAL, QGIS, etc.

This is documented at https://planetarycomputer.microsoft.com/docs/concepts/sas/.

https://gist.github.com/TomAugspurger/4cd0e70c51f7af8d6b1d747c249ea4c4#gistcomment-3763228 has a few ideas from @rolfsimoes about how this could be incorporated into rstac.

**Comment by TomAugspurger** [comment]
Thanks @OldLipe! So this is already on CRAN at https://cran.r-project.org/web/packages/rstac/index.html?

I'll get the updates deployed to the Planetary Computer's staging environment today to try it out.

**Comment by OldLipe** [comment]
Hi @TomAugspurger. Yes, the release version is already on CRAN. 

If you have questions, please contact us.

**Comment by TomAugspurger** [comment]
I just confirmed that I was able to use `items_sign(sign_fn = sign_planetary_computer())` to sign a collecion of items. Thanks!

Perhaps a separate issue, but I seem to be getting a 400 error when trying to use `bbox` from the rstac README:

```R
stac_obj <- stac("https://planetarycomputer.microsoft.com/api/stac/v1/") %>%
 stac_search(collections = "sentinel-2-l2a",
             bbox = c(-47.02148, -12.98314, -42.53906,-17.35063)) %>%
 get_request()
```

that raises 

```
Error: HTTP status '400'. Invalid parameters provided
Traceback:

1. stac("https://planetarycomputer.microsoft.com/api/stac/v1/") %>% 
 .     stac_search(collections = "sentinel-2-l2a", bbox = c(-47.02148, 
 .         -12.98314, -42.53906, -17.35063)) %>% get_request()
2. get_request(.)
3. after_response(q, res = res)
4. after_response.search(q, res = res)
5. content_response(res, "200", c("application/geo+json", "application/json"))
6. .error("HTTP status '%s'. %s", status_code, message)
7. stop(sprintf(msg, ...), call. = FALSE)
```

If I swap the second and forth items in the bbox like so, then things work just fine:

```R
stac_obj <- stac("https://planetarycomputer.microsoft.com/api/stac/v1/") %>%
 stac_search(collections = "sentinel-2-l2a",
             bbox = c(-47.02148, -17.35063, -42.53906, -12.98314)) %>%
 get_request()
```

Maybe there's a typo in the README?

**Comment by OldLipe** [comment]
This is an old typo, thanks for letting us know. We will fix it in a hotfix.
