### ISSUE TITLE
Introduce a class and methods to work with Item

### ISSUE THREAD

**Issue by rolfsimoes** [brazil-data-cube/rstac#48]
Introduce class and methods to work with item (one element of `items$feature`).

For example:
```R
item_assets() # get assets
item_bands() # show bands
item_datetime() # get datetime
item_fields() # list fields
item_get() # get value of a field
```

**Comment by OldLipe** [comment]
The funtions `items_assets`, `items_datetime`, and `items_fields` have already been implemented. We have the function `items_reap` in place of `items_get`. Can I close this issue, @rolfsimoes ?

**Comment by rolfsimoes** [comment]
I agree
